export const language = {
  title: 'Countries',
  more: 'More',
  noresult: 'No result found',
  name: 'Name',
  topLevelDomain: 'Domain',
  alpha2Code: 'Alpha 2 Code',
  alpha3Code: 'Alpha 3 Code',
  callingCodes: 'Calling Codes',
  capital: 'Capital',
  altSpellings: 'Alt Spellings',
  region: 'Region',
  subregion: 'Sub Region',
  population: 'Population',
  latlng: 'Latitude / Longitude',
  demonym: 'Demonym',
  area: 'Area',
  gini: 'Gini',
  timezones: 'Timezones',
  borders: 'Borders',
  nativeName: 'Native Name',
  numericCode: 'Numeric Code',
  currencies: 'Currencies',
  languages: 'Languages',
  translations: 'Translations',
  flag: 'Flag Url',
  regionalBlocs: 'Regional Blocs',
  cioc: 'Cioc',
};
